### ISSUE TITLE
Full API implementation?

### ISSUE THREAD

**Issue by dennybaa** [computology/packagecloud-ruby#10]
Hello,

are you planning to implement all the features of API in this gem. For example I wasn't able to find method for https://packagecloud.io/docs/api#resource_packages_method_versions.

**Comment by capotej** [comment]
Yes, we plan to implement the rest of the API as development time permits, but as of now it is incomplete.

We also happily accept contributions: https://github.com/computology/packagecloud-ruby/pull/6
