### ISSUE TITLE
Example at README fails

### ISSUE THREAD

**Issue by pabloh** [computology/packagecloud-ruby#13]
Example for uploading a gem file at README fails.

```ruby
  # Upload Packages
  @client.put_package("test_repo", gem_package)
```

That last raises an error, it should actually be:

```ruby
  # Upload Packages
  @client.put_package("test_repo", gem_pacakge, nil)
```

**Comment by capotej** [comment]
This was actually a bug in `put_package` that I just [fixed](https://github.com/computology/packagecloud-ruby/commit/25c56f986ac0272886bf1729d98ee7cef82626ea) and released a new version for: [1.0.2](https://rubygems.org/gems/packagecloud-ruby/versions/1.0.2)

Thanks for the bug report!

**Comment by pabloh** [comment]
:+1:

**Comment by javabrett** [comment]
This issue could probably be closed.
