### ISSUE TITLE
Package instances can only be used once

### ISSUE THREAD

**Issue by javabrett** [computology/packagecloud-ruby#14]
If you create a `Package` object:

```
full_path = "my_1.1.1_amd64.deb"
pkg = Packagecloud::Package.new(:file => full_path)
```

Then attempt to use it twice:

```
$client.put_package("my", pkg, ""ubuntu/trusty")
$client.put_package("my", pkg, ""ubuntu/vivid")
```

... the second call will fail.  I think this is because the file-descriptor has been fully read to EOF, it is not closed/rewound, so the file-contents in the MIME for the second-call will be empty, resulting in:

```{"repository":["The specified distro does not support the package you've tried to upload"]}```

I'm not sure what the intended lifecycle of a `Package` is, but it seems reasonable to be able to reuse it.  That would probably mean pulling-up from `Client` the file read into that class.  That would also allow the `File` to be closed in the string/path form, which opens the file.

**Comment by capotej** [comment]
Nice catch. I just reproduced this locally.

You are absolutely right in that a `Package` object is designed to be reused (this is why the `distro_version_id` was moved out of the `Package` object and into `put_package` recently)

I'll have a fix up for this shortly. Thanks for the report!

**Comment by capotej** [comment]
Hey @javabrett, I just released 'packagecloud-1.0.3' which should fix this issue. 

Cheers!

**Comment by javabrett** [comment]
Thanks for the fix!

I suppose in my mind this was between making sure that we always rewind the file, versus pulling-up the creation of all the `MIME::Multipart::FormData` instances from `Client` into `Package`, making the latter resource-independent.

The downside with rewinding seems to be:

1. In the string-path version of `Package` constructor, we open a `File` which I expect we don't close anywhere.
1. In the `File` version of `Package` constructor, we require that the `File` passed must remain open for the lifecycle of the `Package` instance.

Those might be OK.  I just thought if we read the package bytes and created the MIMEs we could make `Package` immutable or closer to it.  Should also be more efficient in the case of reusing a package file multiple times, since the file is only read and converted to MIME once.

**Comment by capotej** [comment]
Great points, I opened https://github.com/computology/packagecloud-ruby/issues/16 to track. Thanks again!
