### ISSUE TITLE
Quick question about README regarding Packagecloud::Package inititialization...

### ISSUE THREAD

**Issue by ckuttruff** [computology/packagecloud-ruby#2]
In the gem / rpm examples, an IO object is used by calling open, but the source example is just passing a string to `Packagecloud::Package.new`
https://github.com/computology/packagecloud-ruby#packages

Is this something that should be tweaked, or am I missing some case analysis in your implementation.
Happy to submit a PR, but wanted to make sure I am understanding things properly, cause it looks like read is called on the file object in all cases:
https://github.com/computology/packagecloud-ruby/blob/master/lib/packagecloud/client.rb#L117

Thanks for your work on packagecloud; has been really easy getting started.
Cheers!

**Comment by capotej** [comment]
Ah, yes this is definitely a typo in the docs, thanks for catching it!

I had planned for them to take string (the path) OR io object but never got around to it, and must have left the docs that way.

Glad you're enjoying using packagecloud!

**Comment by ckuttruff** [comment]
Added a PR if my assumption is correct:
https://github.com/computology/packagecloud-ruby/pull/3

**Comment by ckuttruff** [comment]
Thanks for the lightning quick reply!
Enjoy your day / weekend!
