### ISSUE TITLE
check if the file is already taken before performing the upload

### ISSUE THREAD

**Issue by bryanhuntesl** [computology/packagecloud-ruby#24]
I'm pushing riak packages 

1. They get built by a tool and dumped out into a directory on my system.
2. Some script iterates through them (sorry, I'm so used to rsync) - and attempts packagecloud push using [this](https://github.com/bryanhuntesl/packagecloud) docker wrapper for packagecloud (I can't deal with ruby dependency management)

```
D, [2018-04-04T00:05:50.087903 #8] DEBUG -- : create package request timing:   0.200000   0.170000   0.370000 (177.557302)

Pushing /packages/ubuntu-artful/riak_2.2.5rc1-1_amd64.deb... error (skipping):

        filename: has already been taken
```

But what I notice is, these are big packages ~60MB in size. My internet is... well... upload speeds are pathetic, and the entire upload completes, and the server (presumably) sends back a failure after the entire file has uploaded.

What would be nice, would be if the file was hashed like rysnc does, hash compared with the server, and if the file with that checksum existed, just don't upload the file. 

This would greatly enhance the user experience.

**Comment by tonylambiris** [comment]
@bryanhuntesl I think I suggested this a while ago to them -- would've saved me a bunch of time uploading `.src.rpms` only to find out they were already up there before-hand.

**Comment by tonylambiris** [comment]
@bryanhuntesl I just pushed a bunch of changes to my fork of pkgcloud (written in go): https://github.com/tonylambiris/pkgcloud

I just committed a change that will search for the filename before continuing with upload:
https://github.com/tonylambiris/pkgcloud/commit/4f67f66941773130aaa5fa52a6d1576ab077d73b

Let me know how that works out for ya.

**Comment by ghost** [comment]
Oh that's cool - thank @tonylambiris - hey, my golang knowledge is ~ 0 . I was reading the following : 

https://github.com/tonylambiris/pkgcloud/commit/4f67f66941773130aaa5fa52a6d1576ab077d73b#diff-eb4776873fe0d47a2bd7efdb0e723ed3L45 

`client.Destroy(target.repo+"/"+target.distro, path.Base(pkg)); err != nil ` 

I would guess that means it's removing the existing file, or am I way off the mark ?

**Comment by tonylambiris** [comment]
@bryanhuntesl Yeah `client.Destroy()` deletes the package that was passed in on the command line from the remote repository:
```
➜ ./pkgcloud-yank company/repo/el/7 ~/builds/rpms/go-srpm-macros-2-16.el7.csos.*.rpm
Yanking 2 package(s) from company/repo/el/7 ...
go-srpm-macros-2-16.el7.repo.src.rpm ... OK
go-srpm-macros-2-16.el7.repo.noarch.rpm ... OK
```

**Comment by ghost** [comment]
Hmm what I was looking for was more that it would check if the file existed, then perform the upload. 

At the moment, it uploads the entire file before checking if it already exists on the server - which is slow, and wasteful of bandwidth.

I typically run against a directory (actually a docker volume) where my artefacts are incrementally generated, I'm just a bit used to rsync (if source and destination are identical, skip) behavior.

**Comment by tonylambiris** [comment]
@bryanhuntesl it does exactly that, here is where it checks before attempting a push:
https://github.com/tonylambiris/pkgcloud/blob/4f67f66941773130aaa5fa52a6d1576ab077d73b/cmd/pkgcloud-push/main.go#L47-L54

**Comment by ghost** [comment]
AH ! Nice work @tonylambiris - I'm gonna need to give it a spin. Are you going to push your changes upstream to mlafeldt/pkgcloud or is that project unmaintained now?

**Comment by tonylambiris** [comment]
@bryanhuntesl I'm rolling with my own for -- the original maintainer I forked from hadn't made any commits since April 2017 (not including the latest pull-request that was merged).

Thanks for checking it out! :+1:

**Comment by ghost** [comment]
Thanks Tony for stepping up to maintain. Maybe original dev will hand over
or give maintainer status if he's otherwise occupied. Anyhow, thanks again.

**Comment by tonylambiris** [comment]
@bryanhuntesl quick update, I began merging both commands into one -- still could probably use some general clean-ups (nothing big or special) but otherwise:
```
➜ pkgcloud
Usage: pkgcloud <push/yank> user/repo[/distro/version] /path/to/packages
```
:metal:
